"""empty message

Revision ID: 19bd8781637f
Revises: 6e77cc0aac2a
Create Date: 2019-05-30 14:46:44.707025

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '19bd8781637f'
down_revision = '6e77cc0aac2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jj_measurement', 'Rlwarm')
    op.drop_column('jj_measurement', 'Tc')
    op.drop_column('jj_measurement', 'Rscold')
    op.drop_column('jj_measurement', 'Rswarm')
    op.drop_column('jj_measurement', 'Rlcold')
    op.add_column('via_measurement', sa.Column('Imax', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('via_measurement', 'Imax')
    op.add_column('jj_measurement', sa.Column('Rlcold', mysql.FLOAT(), nullable=True))
    op.add_column('jj_measurement', sa.Column('Rswarm', mysql.FLOAT(), nullable=True))
    op.add_column('jj_measurement', sa.Column('Rscold', mysql.FLOAT(), nullable=True))
    op.add_column('jj_measurement', sa.Column('Tc', mysql.FLOAT(), nullable=True))
    op.add_column('jj_measurement', sa.Column('Rlwarm', mysql.FLOAT(), nullable=True))
    # ### end Alembic commands ###
