"""Trying Base.metadata_v3

Revision ID: 2b98328a4a89
Revises: 
Create Date: 2019-05-23 15:33:50.448869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b98328a4a89'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wafer', sa.Column('comment', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wafer', 'comment')
    # ### end Alembic commands ###
