"""adding in temporary index used for new measureRN function

Revision ID: 47b5463b76a6
Revises: 635a1e48d507
Create Date: 2019-06-19 11:47:02.975202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47b5463b76a6'
down_revision = '635a1e48d507'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jj_measurement', sa.Column('tedindex', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jj_measurement', 'tedindex')
    # ### end Alembic commands ###
