"""Added Tc measurement for Crossbars

Revision ID: 635a1e48d507
Revises: d91c20f2f346
Create Date: 2019-06-06 13:29:37.287100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '635a1e48d507'
down_revision = 'd91c20f2f346'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crossbar_measurement', sa.Column('Tc', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('crossbar_measurement', 'Tc')
    # ### end Alembic commands ###
