"""empty message

Revision ID: 6e77cc0aac2a
Revises: 3d1253397eae
Create Date: 2019-05-29 10:54:55.877426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e77cc0aac2a'
down_revision = '3d1253397eae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jj_measurement', sa.Column('Tc', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jj_measurement', 'Tc')
    # ### end Alembic commands ###
