"""Added missing_width

Revision ID: d2ac9ca3feca
Revises: a31f0bf21034
Create Date: 2019-07-24 14:52:11.647616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2ac9ca3feca'
down_revision = 'a31f0bf21034'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wafer', sa.Column('missing_width', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wafer', 'missing_width')
    # ### end Alembic commands ###
